#!/bin/zsh
#PBS -l nodes=1:ppn=1
#PBS -N rna_bam2Fq
#PBS -t 1-30

source ${PBS_O_WORKDIR}/../pbs_helper_functions.bash

cd "${WORK_PATH}"

echo "In ${WORK_PATH}"

files=($(cat samples.txt))
SAMPLE="${files[$PBS_ARRAYID]}"

~/bin/bamToFastq -i "unmapped/${SAMPLE}_qsort.bam" -fq "unmapped/${SAMPLE}_1.fq" -fq2 "unmapped/${SAMPLE}_2.fq"
rm "unmapped/${SAMPLE}_qsort.bam"
gzip "unmapped/${SAMPLE}_1.fq"
gzip "unmapped/${SAMPLE}_2.fq"

stageout
